name: expandable_search_bar_plus
description: >
  A modern, customizable, and smooth expandable search bar widget for Flutter.
  Supports tap and hover (for web/desktop), with full controller access to open or close programmatically.
version: 1.0.1
homepage: https://github.com/fandiidnaf/expandable_search_bar_plus
repository: https://github.com/fandiidnaf/expandable_search_bar_plus
issue_tracker: https://github.com/fandiidnaf/expandable_search_bar_plus/issues
documentation: https://pub.dev/documentation/expandable_search_bar_plus/latest/
topics:
  - search
  - animation
  - ui
  - widget

environment:
  sdk: ^3.8.1
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # No assets or fonts needed for this package
